apiVersion: batch/v1
kind: Job
metadata:
  name: mnist-training-job
spec:
  template:
    metadata:
      name: mnist-training-job
    spec:
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-tesla-t4
      containers:
        - name: mnist-training
          image: cslecrone/final-project-mnist:v1
          command: ["/usr/local/bin/python3", "/app/main.py"]
          resources:
            limits:
              nvidia.com/gpu: "1"
              cpu: "2"
              memory: 4096Mi
            requests:
              cpu: "2"
              memory: 4096Mi

      restartPolicy: Never
