apiVersion: batch/v1
kind: Job
metadata:
  name: a100-gcn-training-job-v2
spec:
  template:
    metadata:
      name: a100-gcn-training-job-v2
    spec:
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-tesla-a100
      containers:
        - name: gcn-training
          image: virajparikh199725/final-project-gcn:latest
          command: ["python3", "main.py"]
          resources:
            limits:
              nvidia.com/gpu: "1"
              cpu: "6"
              memory: 64Gi
            requests:
              nvidia.com/gpu: "1"
              cpu: "6"
              memory: 32Gi

      restartPolicy: Never
