apiVersion: batch/v1
kind: Job
metadata:
  name: mnist-training-job
spec:
  template:
    metadata:
      name: mnist-training-job
    spec:
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-l4
      containers:
        - name: mnist-training
          image: cslecrone/final-project-mnist:v9
          command: ["sleep", "1000"]
          resources:
            limits:
              nvidia.com/gpu: "1"
              cpu: "6"
              memory: 64Gi
            requests:
              nvidia.com/gpu: "1"
              cpu: "6"
              memory: 32Gi

      restartPolicy: Never
